// Generated by CoffeeScript 1.8.0
(function() {

  var assert = require('assert');
  var _ = require("lodash");
  var Logic = require("../query");

  _.mixin(Logic);

  describe("Underscore Query Tests", function() {

    it("Handles JSON values", function() {
      var rows = [
        { Q17: "[1,2,3]"},
        { Q17: [1,2,3]},
        { Q17: "1"},
        { Q17: 1}
      ]
      var result = _.query(rows, { Q17: 1});
      assert.equal(result.length,   4)


    });
  });

}).call(this);