// Generated by CoffeeScript 1.8.0
(function () {

  var assert = require('assert');
  var _ = require("lodash");
  var Logic = require("../query");

  _.mixin(Logic);

  describe("Underscore Query Tests", function () {

    it('compares numbers quickly', function (done) {
      this
      var rows = []
      for (var i = 0; i < 1000000; i++) {
        rows.push({i: i, v: Math.random() * 1000})
      }

      var start = new Date();
      res = _.query(rows, {a: {$lte: 500}})
      var end = new Date();
      var duration = end - start
      console.log(duration)
      assert(duration < 1000)
      done();
    })
  });

}).call(this);